### ISSUE TITLE
Error Generating XLIFF

### ISSUE THREAD

**Issue by it-ribe** [LauraNicolas/al-language-tools#21]
Has anyone experienced this error?
It happens in a project updated to version 17, but other projects dont have this error.
I have checked all translations changed since the last working solution, but cant find any problems.

![image](https://user-images.githubusercontent.com/42299148/95653250-a8324a00-0af7-11eb-8dab-9f9a2f38c697.png)

**Comment by AndrasSallai** [comment]
I have same, the "XLIFF files generation started" shows, after some minutes it is gone and not produced any translation file.

**Comment by it-ribe** [comment]
I restored a backup of App.json and change the settings to match the current file, and then it worked.
